### ISSUE TITLE
Upgrade to 3.0

### ISSUE THREAD

**Issue by kinduff** [kinduff/spree_reffiliate#10]

**Comment by renewsoqv** [comment]
+1

**Comment by Vickris** [comment]
please provide support for spree 3.0

**Comment by Yaroslav-F** [comment]
+1

**Comment by BeDepraved** [comment]
+1 on this!

**Comment by kinduff** [comment]
@renewsoqv @Vickris @Yaroslav-F @BeDepraved Working on it, sorry for the delay.

**Comment by BeDepraved** [comment]
@kinduff you are a life saver! I've been trying to incorporate 3rd party stuff to do this. Do you have an eta? Do you need help? Do you need a bribe? Don't be sorry for the delay you provide something needed and don't ask for anything, btw!

**Comment by kinduff** [comment]
@BeDepraved Most of the features are good as they are, the only reintegration I'll need to do is on the frontend side. Thanks for the words, I'll keep this issue posted.

**Comment by fraz017** [comment]
+1 for this

**Comment by iwz** [comment]
Was the work on 3.0 support left around anywhere?

**Comment by kinduff** [comment]
@iwz @fraz017 @BeDepraved Repo was moved to an updated fork, here's the 3.0 support https://github.com/vinsol-spree-contrib/spree_reffiliate/tree/3-0-stable
