### ISSUE TITLE
supported spree versions..?

### ISSUE THREAD

**Issue by shivareddy547** [kinduff/spree_reffiliate#11]
Hi,

I am trying to install this extension with spree stable 2.0 version but i am facing below error while installing.

spree_reffiliate (>= 0) ruby depends on
      spree_core (~> 2.3.1) ruby

    spree (>= 0) ruby depends on
      spree_frontend (= 2.0.14.beta) ruby depends on
        spree_core (2.0.14.beta)

Please help me.

Thanks
Shiva.A

**Comment by kinduff** [comment]
@shivareddy547 are you using the rubygems version or the bleeding edge version?
