### ISSUE TITLE
Reward users that refer new users

### ISSUE THREAD

**Issue by haukurhrafn** [kinduff/spree_reffiliate#16]
Is it possible to set it up so that users that refer new users get rewards?

**Comment by kinduff** [comment]
@haukurhrafn not possible with the current setup but the feature should be pretty straight forward. Thinking about making a PR?

**Comment by haukurhrafn** [comment]
@kinduff I'm interested yes, but not sure how it would be implemented. Could it be done with a promotion action?

**Comment by kinduff** [comment]
@haukurhrafn Yes! A promotion rule is enough (see current promotions for an example). Also, remember that the method `User.referral_count` will return the referred count. You could set the promotion rule to compare a desired int is greater than the count.

```
Must have referred more than [int input] users
```
